const DisplayContexts = {
  SHOW_INSTALLED_COURSES: 'SHOW_INSTALLED_COURSES',
  SHOW_ACCOUNT_COURSES: 'SHOW_ACCOUNT_COURSES',
  SHOW_SEARCH_COURSES: 'SHOW_SEARCH_COURSES',
};

export default DisplayContexts;
